Я как пользователь хочу быстро писать US, чтобы экономить время

реверс всей строки


+*In[5]:*+
[source, ipython3]
----
string = "Я как пользователь хочу быстро писать US, чтобы экономить время"
revers = string[::-1]
print(revers)
----


+*Out[5]:*+
----
ямерв ьтимонокэ ыботч ,SU ьтасип ортсыб учох ьлетавозьлоп как Я
----

реверс букв в словах строки с сохранением последовательности


+*In[11]:*+
[source, ipython3]
----
string=input()
for n in string.split():
    print(n[::-1],end=' ')
----


+*Out[11]:*+
----
Я как пользователь хочу быстро писать US, чтобы экономить время
Я как ьлетавозьлоп учох ортсыб ьтасип ,SU ыботч ьтимонокэ ямерв ----


+*In[24]:*+
[source, ipython3]
----
role = input('Введите роль, от лица которого исходит требование')  
wish = input('Введите желаемое требование') 
result = input('Введите желаемый результат') 
d = ('Я как', role, 'хочу', wish, ',', 'чтобы', result)
print(d)
# d = str
 for n in d.split():
     print(n[::-1],end=' ')
----


+*Out[24]:*+
----

      File "<ipython-input-24-b7d060c33a14>", line 7
        for n in d.split():
        ^
    IndentationError: unexpected indent
    

----


+*In[47]:*+
[source, ipython3]
----
role = input('Введите роль, от лица которого исходит требование ')  
wish = input('Введите желаемое требование ') 
result = input('Введите желаемый результат ') 
print (('Я', 'как', role, 'хочу', wish, ',', 'чтобы', result)[::-1])

----


+*Out[47]:*+
----
Введите роль, от лица которого исходит требование rtyui
Введите желаемое требование dfghj
Введите желаемый результат cvbn
('cvbn', 'чтобы', ',', 'dfghj', 'хочу', 'rtyui', 'как', 'Я')
----


+*In[42]:*+
[source, ipython3]
----
role = input('Введите роль, от лица которого исходит требование ')  
wish = input('Введите желаемое требование ') 
result = input('Введите желаемый результат ') 
print ('Я', 'как', role, 'хочу', wish, ',', 'чтобы', result)
''.join(reversed())
----


+*Out[42]:*+
----
Введите роль, от лица которого исходит требование dfgh
Введите желаемое требование df
Введите желаемый результат xcv
Я как dfgh хочу df , чтобы xcv


    ---------------------------------------------------------------------------

    TypeError                                 Traceback (most recent call last)

    <ipython-input-42-002c5b2ce5fd> in <module>
          3 result = input('Введите желаемый результат ')
          4 print ('Я', 'как', role, 'хочу', wish, ',', 'чтобы', result)
    ----> 5 ''.join(reversed())
    

    TypeError: reversed expected 1 argument, got 0

----


+*In[35]:*+
[source, ipython3]
----
x = 'Я как пользователь хочу быстро писать US, чтобы экономить время'
line = ''.join(reversed(x))
line
----


+*Out[35]:*+
----'ямерв ьтимонокэ ыботч ,SU ьтасип ортсыб учох ьлетавозьлоп как Я'----
